### PR TITLE
Fixing application.scss

### PR DESCRIPTION
**Pull request by nicholashibberd**

### CODE REVIEW

**Comment by corriehibberd** [comment]
I've merged your changes, how do I get it down onto my machine?

**Comment by nicholashibberd** [comment]
git pull

**Comment by corriehibberd** [comment]
I added the changes to the custom and application files by hand, but there seemed to be lots of changes to bin files - was that when you forked the app, and should I be including them as well?

Date: Tue, 3 Feb 2015 14:58:32 -0800

**Comment by nicholashibberd** [comment]
Yes I added them as well. They're fine. You should use "bin/rails server"
instead of "bundle exec rails server". New in Rails 4.

**Comment by corriehibberd** [comment]
I just go "rails s" when I want to use the local server - seems to work.

Date: Wed, 4 Feb 2015 02:52:35 -0800

**Pull request merged**
